import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from '@/components/presentation'
import NavBar from '@/components/navbar'
import Valeurs from '@/components/valeurs'
import Rencontre from '@/components/rencontre'
import Innovation from '@/components/innovation'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <NavBar/>
      <main>
        <Hero/>
        <Valeurs/>
        <Rencontre/>
        <Innovation/>
      </main>
    </>
  )
}
